# Generated by Django 3.0.8 on 2020-07-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
