# Generated by Django 3.0.8 on 2020-07-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationalities', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationalities.Nationality'),
        ),
    ]
