# Generated by Django 3.0.8 on 2020-07-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20200725_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='division',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
