# Generated by Django 3.0.8 on 2020-07-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_league'),
        ('foot', '0001_initial'),
        ('nationalities', '0001_initial'),
        ('player_positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(blank=True, default='https://cdn.sofifa.com/players/notfound_0_240.png', max_length=300)),
                ('short_name', models.CharField(max_length=300)),
                ('long_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('height_cm', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('team_jersey_number', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationalities.Nationality')),
                ('player_positions', models.ManyToManyField(related_name='player_positions', to='player_positions.PlayerPosition')),
                ('preferred_foot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foot.Foot')),
                ('team_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_position', to='player_positions.PlayerPosition')),
            ],
        ),
    ]
